from db import Base
from sqlalchemy import Column, Integer, DateTime, Float

class DadoCLP(Base):
    """
    Modelo dos dados do CLP
    """
    __tablename__ = 'dadoclp'
    id = Column(Integer, primary_key=True)
    timestamp = Column(DateTime)
    tipo_motor = Column(Integer)
    tipo_comp = Column(Integer)
    temperatura_tit1 = Column(Float)
    temperatura_tit2 = Column(Float)
    pressao_pit1 = Column(Float)
    pressao_pit2 = Column(Float)
    pressao_pit3 = Column(Float)
    vazao_saida = Column(Float)
    velocidade_saida = Column(Float)
    temp_ar_saida = Column(Float)
    freq_motor = Column(Float)
    torque_motor_axial = Column(Float)
    torque_motor_radial = Column(Float)
    temperatura_R = Column(Float)
    temperatura_S = Column(Float)
    temperatura_T = Column(Float)
    temperatura_Carc = Column(Float)
    corrente_R = Column(Integer)
    corrente_S = Column(Integer)
    corrente_T = Column(Integer)
    corrente_N = Column(Integer)
    corrente_Media = Column(Integer)
    tensao_RS = Column(Integer)
    tensao_ST = Column(Integer)
    tensao_TR = Column(Integer)
    potencia_ativa_R = Column(Integer)
    potencia_ativa_S = Column(Integer)
    potencia_ativa_T = Column(Integer)
    potencia_ativa_Total = Column(Integer)
    fp_R = Column(Integer)
    fp_S = Column(Integer)
    fp_T = Column(Integer)
    fp_Total = Column(Integer)
    corrente_R_co = Column(Integer)
    corrente_S_co = Column(Integer)
    corrente_T_co = Column(Integer)
    corrente_N_co = Column(Integer)
    corrente_Media_co = Column(Integer)
    tensao_RS_co = Column(Integer)
    tensao_ST_co = Column(Integer)
    tensao_TR_co = Column(Integer)
    potencia_ativa_R_co = Column(Integer)
    potencia_ativa_S_co = Column(Integer)
    potencia_ativa_T_co = Column(Integer)
    potencia_ativa_Total_co = Column(Integer)
    fp_R_co = Column(Integer)
    fp_S_co = Column(Integer)
    fp_T_co = Column(Integer)
    fp_Total_co = Column(Integer)
